# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: ['db/*.scroll', 'index.html', 'pages/*.html', '*.html']
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install .
          npm install n-readlines fs path
          node build
      - name: Archive code index
      - uses: actions/upload-artifact@v3
        with:
          name: upload index.html
          path: index.html
      - run: |   
          node build_profiles
      - name: Archive production artifacts profiles pages
      - uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            pages
            pages/**/*.html
#       - name: Commit files # transfer the new html files back into the repository
#         run: git config --global user.email "adriantintpilver@gmail.com"
#              git config --global user.name "adriantintpilver"
#              git add ./docs
#              git commit -m "Updating the repository GitHub html pages in the docs folder"
#       - name: Push changes # push the output folder to your repo
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           force: true





